let x,y;
x = parseInt(prompt("enter the first number"));
y = parseInt(prompt("enter the second number"));
let a = x+y;
let b = x-y;
let c = x*y;
let d = x/y;
alert("The sum of given number is:"+a);
alert("The difference of given number is:"+b);
alert("The product of given number is:"+c);
alert("The quotient of given number is:"+d);